spring:
  application:
    name: job
  datasource:
    name: batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${vm_ip:127.0.0.1}:3306/${spring.datasource.name}?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ${mysql_password:123456qaz}
    hikari:
      pool-name: MyPool
      connection-timeout: 60000
      maximum-pool-size: 60
      minimum-idle: 10
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 180000
      connection-test-query: select 1
  datasource-read:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${vm_ip:127.0.0.1}:3306/read?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ${mysql_password:123456qaz}
  datasource-write:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${vm_ip:127.0.0.1}:3306/write?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ${mysql_password:123456qaz}

mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      # 主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: deleteFlag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
