spring:
  application:
    name: job
  datasource:
    master:
      name: batch
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://${vm_ip:127.0.0.1}:3306/${spring.datasource.master.name}?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: ${mysql_password:123456qaz}
    read:
      name: read
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://${vm_ip:127.0.0.1}:3306/${spring.datasource.read.name}?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: ${mysql_password:123456qaz}
    write:
      name: write
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://${vm_ip:127.0.0.1}:3306/${spring.datasource.write.name}?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: ${mysql_password:123456qaz}